repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

missingFileHandler: Error

releases:
  - name: "gitlab-secrets"
    namespace: "gitlab"
    labels:
      chart: "raw"
      repo: "incubator"
      namespace: "gitlab"
      vendor: "helm"
    chart: "incubator/raw"
    version: "0.2.3"
    wait: true
    atomic: true
    cleanupOnFail: true
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ requiredEnv "GITLAB_INITIAL_ROOT_PASSWORD_SECRET_NAME" | quote }}
            type: Opaque
            stringData:
              {{ requiredEnv "GITLAB_INITIAL_ROOT_PASSWORD_SECRET_KEY" }}: {{ requiredEnv "GITLAB_INITIAL_ROOT_PASSWORD" | quote }}
