{{- $gitlabHostName := requiredEnv "GITLAB_GITLAB_HOST_NAME" }}
{{- $gitlabApiToken := requiredEnv "GITLAB_API_TOKEN" }}
{{- $jenkinsHostName := requiredEnv "JENKINS_HOST_NAME" }}
{{- $jenkinsId := requiredEnv "JENKINS_ID" }}
{{- $jenkinsSecret := requiredEnv "JENKINS_SECRET" }}
{{- $jenkinsAdminEmail := requiredEnv "JENKINS_ADMIN_EMAIL" }}
{{- $initialAdminCredsSecretName := requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_SECRET_NAME" }}
{{- $initialAdminCredsUserKey := requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_USER_KEY" }}
{{- $initialAdminCredsPasswordKey := requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_PASSWORD_KEY" }}
{{- $clusterIssuer := requiredEnv "CLUSTER_ISSUER" }}

repositories:
  - name: "jenkins"
    url: "https://charts.jenkins.io"

missingFileHandler: Error

releases:
  - name: "jenkins"
    namespace: "jenkins"
    labels:
      chart: "jenkins"
      repo: "jenkins"
      namespace: "jenkins"
      vendor: "jenkins"
    chart: "jenkins/jenkins"
    version: "2.17.1"
    wait: true
    atomic: true
    cleanupOnFail: true
    timeout: 1200
    values:
      - master:
          image: "jenkins/jenkins"
          tag: "2.249.3-lts-centos7"
          imagePullPolicy: "IfNotPresent"
          admin:
            existingSecret: {{$initialAdminCredsSecretName | quote}}
            userKey: {{$initialAdminCredsUserKey | quote}}
            passwordKey: {{$initialAdminCredsPasswordKey | quote}}
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
          jenkinsUrl: "https://{{$jenkinsHostName}}"
          jenkinsAdminEmail: {{$jenkinsAdminEmail | quote}}
          installPlugins:
            - kubernetes:1.27.7
            - workflow-job:2.40
            - workflow-aggregator:2.6
            - workflow-cps-global-lib:2.18
            - pipeline-stage-view:2.19
            - credentials-binding:1.24
            - gitlab-oauth:1.10
            - gitlab-plugin:1.5.13
            - matrix-auth:2.6.6
            - configuration-as-code:1.47
            - blueocean:1.24.3
          additionalPlugins:
            - ace-editor:1.1
            - antisamy-markup-formatter:2.1
            - apache-httpcomponents-client-4-api:4.5.13-1.0
            - authentication-tokens:1.4
            - blueocean-autofavorite:1.2.4
            - blueocean-bitbucket-pipeline:1.24.6
            - blueocean-commons:1.24.6
            - blueocean-config:1.24.6
            - blueocean-core-js:1.24.6
            - blueocean-dashboard:1.24.6
            - blueocean-display-url:2.4.1
            - blueocean-events:1.24.6
            - blueocean-git-pipeline:1.24.6
            - blueocean-github-pipeline:1.24.6
            - blueocean-i18n:1.24.6
            - blueocean-jira:1.24.6
            - blueocean-jwt:1.24.6
            - blueocean-personalization:1.24.6
            - blueocean-pipeline-api-impl:1.24.6
            - blueocean-pipeline-editor:1.24.6
            - blueocean-pipeline-scm-api:1.24.6
            - blueocean-rest:1.24.6
            - blueocean-rest-impl:1.24.6
            - blueocean-web:1.24.6
            - bootstrap4-api:4.6.0-3
            - bouncycastle-api:2.20
            - branch-api:2.6.2
            - checks-api:1.7.0
            - cloudbees-bitbucket-branch-source:2.9.7
            - cloudbees-folder:6.15
            - command-launcher:1.2
            - credentials:2.3.17
            - display-url-api:2.3.4
            - durable-task:1.35
            - echarts-api:5.0.2-1
            - favorite:2.3.2
            - font-awesome-api:5.15.2-2
            - git:4.6.0
            - git-client:3.6.0
            - git-server:1.9
            - github:1.33.1
            - github-api:1.123
            - github-branch-source:2.9.7
            - handlebars:3.0.8
            - handy-uri-templates-2-api:2.1.8-1.0
            - htmlpublisher:1.25
            - jackson2-api:2.12.2
            - jdk-tool:1.0
            - jenkins-design-language:1.24.6
            - jira:3.2.1
            - jjwt-api:0.11.2-9.c8b45b8bb173
            - jquery3-api:3.6.0-1
            - jsch:0.1.55.2
            - junit:1.49
            - kubernetes-client-api:4.13.2-1
            - kubernetes-credentials:0.8.0
            - lockable-resources:2.10
            - mailer:1.34
            - matrix-project:1.18
            - momentjs:1.1.1
            - okhttp-api:3.14.9
            - pipeline-build-step:2.13
            - pipeline-graph-analysis:1.10
            - pipeline-input-step:2.12
            - pipeline-milestone-step:1.3.2
            - pipeline-model-api:1.8.4
            - pipeline-model-definition:1.8.4
            - pipeline-model-extensions:1.8.4
            - pipeline-rest-api:2.19
            - pipeline-stage-step:2.5
            - pipeline-stage-tags-metadata:1.8.4
            - plain-credentials:1.7
            - plugin-util-api:2.1.0
            - popper-api:1.16.1-2
            - pubsub-light:1.13
            - scm-api:2.6.4
            - script-security:1.76
            - snakeyaml-api:1.27.0
            - sse-gateway:1.24
            - ssh-credentials:1.18.1
            - structs:1.22
            - token-macro:2.13
            - trilead-api:1.0.13
            - variant:1.4
            - workflow-api:2.45
            - workflow-basic-steps:2.22
            - workflow-cps:2.90
            - workflow-durable-task-step:2.38
            - workflow-multibranch:2.23
            - workflow-scm-step:2.12
            - workflow-step-api:2.23
            - workflow-support:3.8
          initializeOnce: true
          overwritePlugins: true
          enableRawHtmlMarkupFormatter: true
#          scriptApproval:
#            - "method java.util.Base64$Decoder decode java.lang.String"
#            - "new java.lang.String byte[]"
#            - "staticMethod java.util.Base64 getDecoder"
          JCasC:
            enabled: true
            defaultConfig: true
            configScripts:
              welcome-message: |
                jenkins:
                  systemMessage: "Ephemeral Virtual Training Range (EVTR)"
              credentials: |
                credentials:
                  system:
                    domainCredentials:
                      - credentials:
                          - gitLabApiTokenImpl:
                              scope: SYSTEM
                              id: gitlab_token
                              apiToken: "{{$gitlabApiToken}}"
                              description: "Gitlab Token"
                          - usernamePassword:
                              scope: GLOBAL
                              id: gitlab_credentials
                              username: root
                              password: "{{$gitlabApiToken}}"
              gitlab: |
                unclassified:
                  gitlabconnectionconfig:
                    connections:
                      - apiTokenId: gitlab_token
                        clientBuilderId: "autodetect"
                        connectionTimeout: 20
                        ignoreCertificateErrors: true
                        name: "gitlab"
                        readTimeout: 10
                        url: "https://{{$gitlabHostName}}"
            securityRealm: |-
              gitLab:
                clientID: "{{$jenkinsId}}"
                clientSecret: "{{$jenkinsSecret}}"
                gitlabApiUri: "https://{{$gitlabHostName}}"
                gitlabWebUri: "https://{{$gitlabHostName}}"
            authorizationStrategy: |-
              projectMatrix:
                permissions:
                - "Overall/Administer:root"
                - "Overall/Read:authenticated"
          sidecars:
            configAutoReload:
              enabled: true
              resources:
                requests:
                  cpu: 50m
                  memory: 50Mi
                limits:
                  cpu: 100m
                  memory: 100Mi
          ingress:
            enabled: true
            paths: []
            apiVersion: "networking.k8s.io/v1beta1"
            labels: {}
            annotations:
              cert-manager.io/cluster-issuer: {{$clusterIssuer | quote}}
              kubernetes.io/ingress.class: "nginx"
              kubernetes.io/ingress.provider: "nginx"
            hostName: {{$jenkinsHostName | quote}}
            tls:
              - secretName: "tls-{{$jenkinsHostName}}"
                hosts:
                  - {{$jenkinsHostName | quote}}
          healthProbeLivenessInitialDelay: 180
        persistence:
          enabled: true
          storageClass: efs
