repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

missingFileHandler: Error

releases:
  - name: "jenkins-secrets"
    namespace: "jenkins"
    labels:
      chart: "raw"
      repo: "incubator"
      namespace: "gitlab"
      vendor: "helm"
    chart: "incubator/raw"
    version: "0.2.3"
    wait: true
    atomic: true
    cleanupOnFail: true
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: {{ requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_SECRET_NAME" | quote }}
            type: Opaque
            stringData:
              {{ requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_USER_KEY" }}: {{ requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_USER_VALUE" | quote }}
              {{ requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_PASSWORD_KEY" }}: {{ requiredEnv "JENKINS_INITIAL_ADMIN_CREDS_PASSWORD_VALUE" | quote }}
